version: '3.1'
services:
  backend:
    build: ./server
    restart: always
    environment:
      - PORT=5000
      - DEBUG=$DEBUG
      - MONGOURI
      - SECRET_KEY
    networks:
      - web-network
    

  frontend:
    build: ./client
    environment:
      - PORT=3000
      - DEBUG=$DEBUG
    networks:
      - web-network

  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    networks:
      - web-network
      
  networks:
    web-network:
      driver:bridge


# docker-compose up -d
# chmod +x entrypoint.sh

# docker-compose logs -f nginx
# docker-compose logs -f backend
# docker-compose logs -f frontend
# docker-compose build backend
# docker-compose run backend
# docker-compose build backend --no-cache
# docker-compose logs -f frontend
# docker-compose build frontend
# docker-compose down
# docker-compose up -d
